[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
counter = "9zqibQV12PiGUAqQae8tmmyJvkjKEs6awPXKVhjJmSCc"

[programs.localnet]
voting_contract = "9zqibQV12PiGUAqQae8tmmyJvkjKEs6awPXKVhjJmSCc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/falguni/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
