[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
voting_app = "75GwYpCopgByConQ6dwwQtM8UYMnJsxWURLJwBp1L2hm"

[programs.devnet]
counter = "75GwYpCopgByConQ6dwwQtM8UYMnJsxWURLJwBp1L2hm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/falguni/.config/solana/id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
